In [1]:
print(1)

1


In [4]:
import numpy as np

In [5]:
b = np.array([1,2])
print(b)

[1 2]


In [6]:
print(b.shape)

(2,)


In [16]:
b =np.full((5,5),1)
b[1:4,1:4] = 0
b[2,2]=9


print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [18]:
a= np.array([[100, 200, 2], [3,10,12], [10,14,9]])



In [21]:
a= a[(a>90) | (a%3==0)]
print(a)

[ 3 12  9]
